#include "cctk.h"

module qlm_em_variables
  use classify
  implicit none
  public
  save
  CCTK_REAL, allocatable, dimension(:,:) :: &
       qlm_em_gxx, qlm_em_gxy, qlm_em_gxz, qlm_em_gyy, qlm_em_gyz, qlm_em_gzz, &
       qlm_em_dgxxx, qlm_em_dgxyx, qlm_em_dgxzx, qlm_em_dgyyx, qlm_em_dgyzx, qlm_em_dgzzx, &
       qlm_em_dgxxy, qlm_em_dgxyy, qlm_em_dgxzy, qlm_em_dgyyy, qlm_em_dgyzy, qlm_em_dgzzy, &
       qlm_em_dgxxz, qlm_em_dgxyz, qlm_em_dgxzz, qlm_em_dgyyz, qlm_em_dgyzz, qlm_em_dgzzz, &
       qlm_em_ddgxxxx, qlm_em_ddgxyxx, qlm_em_ddgxzxx, qlm_em_ddgyyxx, qlm_em_ddgyzxx, qlm_em_ddgzzxx, &
       qlm_em_ddgxxxy, qlm_em_ddgxyxy, qlm_em_ddgxzxy, qlm_em_ddgyyxy, qlm_em_ddgyzxy, qlm_em_ddgzzxy, &
       qlm_em_ddgxxxz, qlm_em_ddgxyxz, qlm_em_ddgxzxz, qlm_em_ddgyyxz, qlm_em_ddgyzxz, qlm_em_ddgzzxz, &
       qlm_em_ddgxxyy, qlm_em_ddgxyyy, qlm_em_ddgxzyy, qlm_em_ddgyyyy, qlm_em_ddgyzyy, qlm_em_ddgzzyy, &
       qlm_em_ddgxxyz, qlm_em_ddgxyyz, qlm_em_ddgxzyz, qlm_em_ddgyyyz, qlm_em_ddgyzyz, qlm_em_ddgzzyz, &
       qlm_em_ddgxxzz, qlm_em_ddgxyzz, qlm_em_ddgxzzz, qlm_em_ddgyyzz, qlm_em_ddgyzzz, qlm_em_ddgzzzz, &
       qlm_em_kxx, qlm_em_kxy, qlm_em_kxz, qlm_em_kyy, qlm_em_kyz, qlm_em_kzz, &
       qlm_em_dkxxx, qlm_em_dkxyx, qlm_em_dkxzx, qlm_em_dkyyx, qlm_em_dkyzx, qlm_em_dkzzx, &
       qlm_em_dkxxy, qlm_em_dkxyy, qlm_em_dkxzy, qlm_em_dkyyy, qlm_em_dkyzy, qlm_em_dkzzy, &
       qlm_em_dkxxz, qlm_em_dkxyz, qlm_em_dkxzz, qlm_em_dkyyz, qlm_em_dkyzz, qlm_em_dkzzz, &
       qlm_em_alpha, &
       qlm_em_betax, qlm_em_betay, qlm_em_betaz, &
       qlm_em_ttt, &
       qlm_em_ttx, qlm_em_tty, qlm_em_ttz, &
       qlm_em_txx, qlm_em_txy, qlm_em_txz, qlm_em_tyy, qlm_em_tyz, qlm_em_tzz, &
       qlm_em_ex, qlm_em_ey, qlm_em_ez, qlm_em_ax, qlm_em_ay, qlm_em_az, &
       qlm_em_daxx, qlm_em_daxy, qlm_em_daxz, qlm_em_dayx, qlm_em_dayy, qlm_em_dayz, &
       qlm_em_dazx, qlm_em_dazy, qlm_em_dazz, &
       qlm_em_phi1, qlm_em_phi2
  CCTK_REAL, allocatable, dimension(:,:) :: &
       qlm_em_dqttt, qlm_em_dqtpt, qlm_em_dqppt, qlm_em_dqttp, qlm_em_dqtpp, qlm_em_dqppp
  
  CCTK_REAL, allocatable, dimension(:,:) :: &
       qlm_em_spin_density
  
  type tetrad_derivs
     ! nabla_ll(a,b) = D_b l_a
     CCTK_REAL    :: nabla_ll(0:3,0:3)
     CCTK_REAL    :: nabla_nn(0:3,0:3)
     CCTK_COMPLEX :: nabla_mm(0:3,0:3)
  end type tetrad_derivs
  type(tetrad_derivs), allocatable, dimension(:,:) :: qlm_em_tetrad_derivs
  
contains
  
  subroutine allocate_variables(ntheta, nphi)
    integer,   intent(in) :: ntheta, nphi
    CCTK_REAL, parameter  :: zero = 0
    integer,   parameter  :: rk = kind(zero)
    type(tetrad_derivs)   :: tetrad_derivs_nan
    
    allocate(qlm_em_gxx(ntheta,nphi))
    allocate(qlm_em_gxy(ntheta,nphi))
    allocate(qlm_em_gxz(ntheta,nphi))
    allocate(qlm_em_gyy(ntheta,nphi))
    allocate(qlm_em_gyz(ntheta,nphi))
    allocate(qlm_em_gzz(ntheta,nphi))
    allocate(qlm_em_dgxxx(ntheta,nphi))
    allocate(qlm_em_dgxyx(ntheta,nphi))
    allocate(qlm_em_dgxzx(ntheta,nphi))
    allocate(qlm_em_dgyyx(ntheta,nphi))
    allocate(qlm_em_dgyzx(ntheta,nphi))
    allocate(qlm_em_dgzzx(ntheta,nphi))
    allocate(qlm_em_dgxxy(ntheta,nphi))
    allocate(qlm_em_dgxyy(ntheta,nphi))
    allocate(qlm_em_dgxzy(ntheta,nphi))
    allocate(qlm_em_dgyyy(ntheta,nphi))
    allocate(qlm_em_dgyzy(ntheta,nphi))
    allocate(qlm_em_dgzzy(ntheta,nphi))
    allocate(qlm_em_dgxxz(ntheta,nphi))
    allocate(qlm_em_dgxyz(ntheta,nphi))
    allocate(qlm_em_dgxzz(ntheta,nphi))
    allocate(qlm_em_dgyyz(ntheta,nphi))
    allocate(qlm_em_dgyzz(ntheta,nphi))
    allocate(qlm_em_dgzzz(ntheta,nphi))
    allocate(qlm_em_ddgxxxx(ntheta,nphi))
    allocate(qlm_em_ddgxyxx(ntheta,nphi))
    allocate(qlm_em_ddgxzxx(ntheta,nphi))
    allocate(qlm_em_ddgyyxx(ntheta,nphi))
    allocate(qlm_em_ddgyzxx(ntheta,nphi))
    allocate(qlm_em_ddgzzxx(ntheta,nphi))
    allocate(qlm_em_ddgxxxy(ntheta,nphi))
    allocate(qlm_em_ddgxyxy(ntheta,nphi))
    allocate(qlm_em_ddgxzxy(ntheta,nphi))
    allocate(qlm_em_ddgyyxy(ntheta,nphi))
    allocate(qlm_em_ddgyzxy(ntheta,nphi))
    allocate(qlm_em_ddgzzxy(ntheta,nphi))
    allocate(qlm_em_ddgxxxz(ntheta,nphi))
    allocate(qlm_em_ddgxyxz(ntheta,nphi))
    allocate(qlm_em_ddgxzxz(ntheta,nphi))
    allocate(qlm_em_ddgyyxz(ntheta,nphi))
    allocate(qlm_em_ddgyzxz(ntheta,nphi))
    allocate(qlm_em_ddgzzxz(ntheta,nphi))
    allocate(qlm_em_ddgxxyy(ntheta,nphi))
    allocate(qlm_em_ddgxyyy(ntheta,nphi))
    allocate(qlm_em_ddgxzyy(ntheta,nphi))
    allocate(qlm_em_ddgyyyy(ntheta,nphi))
    allocate(qlm_em_ddgyzyy(ntheta,nphi))
    allocate(qlm_em_ddgzzyy(ntheta,nphi))
    allocate(qlm_em_ddgxxyz(ntheta,nphi))
    allocate(qlm_em_ddgxyyz(ntheta,nphi))
    allocate(qlm_em_ddgxzyz(ntheta,nphi))
    allocate(qlm_em_ddgyyyz(ntheta,nphi))
    allocate(qlm_em_ddgyzyz(ntheta,nphi))
    allocate(qlm_em_ddgzzyz(ntheta,nphi))
    allocate(qlm_em_ddgxxzz(ntheta,nphi))
    allocate(qlm_em_ddgxyzz(ntheta,nphi))
    allocate(qlm_em_ddgxzzz(ntheta,nphi))
    allocate(qlm_em_ddgyyzz(ntheta,nphi))
    allocate(qlm_em_ddgyzzz(ntheta,nphi))
    allocate(qlm_em_ddgzzzz(ntheta,nphi))
    allocate(qlm_em_kxx(ntheta,nphi))
    allocate(qlm_em_kxy(ntheta,nphi))
    allocate(qlm_em_kxz(ntheta,nphi))
    allocate(qlm_em_kyy(ntheta,nphi))
    allocate(qlm_em_kyz(ntheta,nphi))
    allocate(qlm_em_kzz(ntheta,nphi))
    allocate(qlm_em_dkxxx(ntheta,nphi))
    allocate(qlm_em_dkxyx(ntheta,nphi))
    allocate(qlm_em_dkxzx(ntheta,nphi))
    allocate(qlm_em_dkyyx(ntheta,nphi))
    allocate(qlm_em_dkyzx(ntheta,nphi))
    allocate(qlm_em_dkzzx(ntheta,nphi))
    allocate(qlm_em_dkxxy(ntheta,nphi))
    allocate(qlm_em_dkxyy(ntheta,nphi))
    allocate(qlm_em_dkxzy(ntheta,nphi))
    allocate(qlm_em_dkyyy(ntheta,nphi))
    allocate(qlm_em_dkyzy(ntheta,nphi))
    allocate(qlm_em_dkzzy(ntheta,nphi))
    allocate(qlm_em_dkxxz(ntheta,nphi))
    allocate(qlm_em_dkxyz(ntheta,nphi))
    allocate(qlm_em_dkxzz(ntheta,nphi))
    allocate(qlm_em_dkyyz(ntheta,nphi))
    allocate(qlm_em_dkyzz(ntheta,nphi))
    allocate(qlm_em_dkzzz(ntheta,nphi))
    allocate(qlm_em_alpha(ntheta,nphi))
    allocate(qlm_em_betax(ntheta,nphi))
    allocate(qlm_em_betay(ntheta,nphi))
    allocate(qlm_em_betaz(ntheta,nphi))
    allocate(qlm_em_ttt(ntheta,nphi))
    allocate(qlm_em_ttx(ntheta,nphi))
    allocate(qlm_em_tty(ntheta,nphi))
    allocate(qlm_em_ttz(ntheta,nphi))
    allocate(qlm_em_txx(ntheta,nphi))
    allocate(qlm_em_txy(ntheta,nphi))
    allocate(qlm_em_txz(ntheta,nphi))
    allocate(qlm_em_tyy(ntheta,nphi))
    allocate(qlm_em_tyz(ntheta,nphi))
    allocate(qlm_em_tzz(ntheta,nphi))
    allocate(qlm_em_ex(ntheta,nphi))
    allocate(qlm_em_ey(ntheta,nphi))
    allocate(qlm_em_ez(ntheta,nphi))
    allocate(qlm_em_ax(ntheta,nphi))
    allocate(qlm_em_ay(ntheta,nphi))
    allocate(qlm_em_az(ntheta,nphi))
    allocate(qlm_em_daxx(ntheta,nphi))
    allocate(qlm_em_daxy(ntheta,nphi))
    allocate(qlm_em_daxz(ntheta,nphi))
    allocate(qlm_em_dayx(ntheta,nphi))
    allocate(qlm_em_dayy(ntheta,nphi))
    allocate(qlm_em_dayz(ntheta,nphi))
    allocate(qlm_em_dazx(ntheta,nphi))
    allocate(qlm_em_dazy(ntheta,nphi))
    allocate(qlm_em_dazz(ntheta,nphi))
    allocate(qlm_em_phi1(ntheta,nphi))
    allocate(qlm_em_phi2(ntheta,nphi))
    
    allocate(qlm_em_dqttt(ntheta,nphi))
    allocate(qlm_em_dqtpt(ntheta,nphi))
    allocate(qlm_em_dqppt(ntheta,nphi))
    allocate(qlm_em_dqttp(ntheta,nphi))
    allocate(qlm_em_dqtpp(ntheta,nphi))
    allocate(qlm_em_dqppp(ntheta,nphi))
    
    allocate(qlm_em_tetrad_derivs(ntheta,nphi))
    
    allocate(qlm_em_spin_density(ntheta,nphi))
    
    qlm_em_gxx = TAT_nan()
    qlm_em_gxy = TAT_nan()
    qlm_em_gxz = TAT_nan()
    qlm_em_gyy = TAT_nan()
    qlm_em_gyz = TAT_nan()
    qlm_em_gzz = TAT_nan()
    qlm_em_dgxxx = TAT_nan()
    qlm_em_dgxyx = TAT_nan()
    qlm_em_dgxzx = TAT_nan()
    qlm_em_dgyyx = TAT_nan()
    qlm_em_dgyzx = TAT_nan()
    qlm_em_dgzzx = TAT_nan()
    qlm_em_dgxxy = TAT_nan()
    qlm_em_dgxyy = TAT_nan()
    qlm_em_dgxzy = TAT_nan()
    qlm_em_dgyyy = TAT_nan()
    qlm_em_dgyzy = TAT_nan()
    qlm_em_dgzzy = TAT_nan()
    qlm_em_dgxxz = TAT_nan()
    qlm_em_dgxyz = TAT_nan()
    qlm_em_dgxzz = TAT_nan()
    qlm_em_dgyyz = TAT_nan()
    qlm_em_dgyzz = TAT_nan()
    qlm_em_dgzzz = TAT_nan()
    qlm_em_ddgxxxx = TAT_nan()
    qlm_em_ddgxyxx = TAT_nan()
    qlm_em_ddgxzxx = TAT_nan()
    qlm_em_ddgyyxx = TAT_nan()
    qlm_em_ddgyzxx = TAT_nan()
    qlm_em_ddgzzxx = TAT_nan()
    qlm_em_ddgxxxy = TAT_nan()
    qlm_em_ddgxyxy = TAT_nan()
    qlm_em_ddgxzxy = TAT_nan()
    qlm_em_ddgyyxy = TAT_nan()
    qlm_em_ddgyzxy = TAT_nan()
    qlm_em_ddgzzxy = TAT_nan()
    qlm_em_ddgxxxz = TAT_nan()
    qlm_em_ddgxyxz = TAT_nan()
    qlm_em_ddgxzxz = TAT_nan()
    qlm_em_ddgyyxz = TAT_nan()
    qlm_em_ddgyzxz = TAT_nan()
    qlm_em_ddgzzxz = TAT_nan()
    qlm_em_ddgxxyy = TAT_nan()
    qlm_em_ddgxyyy = TAT_nan()
    qlm_em_ddgxzyy = TAT_nan()
    qlm_em_ddgyyyy = TAT_nan()
    qlm_em_ddgyzyy = TAT_nan()
    qlm_em_ddgzzyy = TAT_nan()
    qlm_em_ddgxxyz = TAT_nan()
    qlm_em_ddgxyyz = TAT_nan()
    qlm_em_ddgxzyz = TAT_nan()
    qlm_em_ddgyyyz = TAT_nan()
    qlm_em_ddgyzyz = TAT_nan()
    qlm_em_ddgzzyz = TAT_nan()
    qlm_em_ddgxxzz = TAT_nan()
    qlm_em_ddgxyzz = TAT_nan()
    qlm_em_ddgxzzz = TAT_nan()
    qlm_em_ddgyyzz = TAT_nan()
    qlm_em_ddgyzzz = TAT_nan()
    qlm_em_ddgzzzz = TAT_nan()
    qlm_em_kxx = TAT_nan()
    qlm_em_kxy = TAT_nan()
    qlm_em_kxz = TAT_nan()
    qlm_em_kyy = TAT_nan()
    qlm_em_kyz = TAT_nan()
    qlm_em_kzz = TAT_nan()
    qlm_em_dkxxx = TAT_nan()
    qlm_em_dkxyx = TAT_nan()
    qlm_em_dkxzx = TAT_nan()
    qlm_em_dkyyx = TAT_nan()
    qlm_em_dkyzx = TAT_nan()
    qlm_em_dkzzx = TAT_nan()
    qlm_em_dkxxy = TAT_nan()
    qlm_em_dkxyy = TAT_nan()
    qlm_em_dkxzy = TAT_nan()
    qlm_em_dkyyy = TAT_nan()
    qlm_em_dkyzy = TAT_nan()
    qlm_em_dkzzy = TAT_nan()
    qlm_em_dkxxz = TAT_nan()
    qlm_em_dkxyz = TAT_nan()
    qlm_em_dkxzz = TAT_nan()
    qlm_em_dkyyz = TAT_nan()
    qlm_em_dkyzz = TAT_nan()
    qlm_em_dkzzz = TAT_nan()
    qlm_em_alpha = TAT_nan()
    qlm_em_betax = TAT_nan()
    qlm_em_betay = TAT_nan()
    qlm_em_betaz = TAT_nan()
    qlm_em_ttt = TAT_nan()
    qlm_em_ttx = TAT_nan()
    qlm_em_tty = TAT_nan()
    qlm_em_ttz = TAT_nan()
    qlm_em_txx = TAT_nan()
    qlm_em_txy = TAT_nan()
    qlm_em_txz = TAT_nan()
    qlm_em_tyy = TAT_nan()
    qlm_em_tyz = TAT_nan()
    qlm_em_tzz = TAT_nan()
    qlm_em_ex = TAT_nan()
    qlm_em_ey = TAT_nan()
    qlm_em_ez = TAT_nan()
    qlm_em_ax = TAT_nan()
    qlm_em_ay = TAT_nan()
    qlm_em_az = TAT_nan()
    qlm_em_daxx = TAT_nan()
    qlm_em_daxy = TAT_nan()
    qlm_em_daxz = TAT_nan()
    qlm_em_dayx = TAT_nan()
    qlm_em_dayy = TAT_nan()
    qlm_em_dayz = TAT_nan()
    qlm_em_dazx = TAT_nan()
    qlm_em_dazy = TAT_nan()
    qlm_em_dazz = TAT_nan()
    qlm_em_phi1 = TAT_nan()
    qlm_em_phi2 = TAT_nan()
    
    qlm_em_dqttt = TAT_nan()
    qlm_em_dqtpt = TAT_nan()
    qlm_em_dqppt = TAT_nan()
    qlm_em_dqttp = TAT_nan()
    qlm_em_dqtpp = TAT_nan()
    qlm_em_dqppp = TAT_nan()
    
    tetrad_derivs_nan%nabla_ll = TAT_nan()
    tetrad_derivs_nan%nabla_nn = TAT_nan()
    tetrad_derivs_nan%nabla_mm = cmplx(TAT_nan(),TAT_nan(),rk)
    qlm_em_tetrad_derivs = tetrad_derivs_nan

    qlm_em_spin_density = TAT_nan()
  end subroutine allocate_variables

  subroutine deallocate_variables
    deallocate(qlm_em_gxx)
    deallocate(qlm_em_gxy)
    deallocate(qlm_em_gxz)
    deallocate(qlm_em_gyy)
    deallocate(qlm_em_gyz)
    deallocate(qlm_em_gzz)
    deallocate(qlm_em_dgxxx)
    deallocate(qlm_em_dgxyx)
    deallocate(qlm_em_dgxzx)
    deallocate(qlm_em_dgyyx)
    deallocate(qlm_em_dgyzx)
    deallocate(qlm_em_dgzzx)
    deallocate(qlm_em_dgxxy)
    deallocate(qlm_em_dgxyy)
    deallocate(qlm_em_dgxzy)
    deallocate(qlm_em_dgyyy)
    deallocate(qlm_em_dgyzy)
    deallocate(qlm_em_dgzzy)
    deallocate(qlm_em_dgxxz)
    deallocate(qlm_em_dgxyz)
    deallocate(qlm_em_dgxzz)
    deallocate(qlm_em_dgyyz)
    deallocate(qlm_em_dgyzz)
    deallocate(qlm_em_dgzzz)
    deallocate(qlm_em_ddgxxxx)
    deallocate(qlm_em_ddgxyxx)
    deallocate(qlm_em_ddgxzxx)
    deallocate(qlm_em_ddgyyxx)
    deallocate(qlm_em_ddgyzxx)
    deallocate(qlm_em_ddgzzxx)
    deallocate(qlm_em_ddgxxxy)
    deallocate(qlm_em_ddgxyxy)
    deallocate(qlm_em_ddgxzxy)
    deallocate(qlm_em_ddgyyxy)
    deallocate(qlm_em_ddgyzxy)
    deallocate(qlm_em_ddgzzxy)
    deallocate(qlm_em_ddgxxxz)
    deallocate(qlm_em_ddgxyxz)
    deallocate(qlm_em_ddgxzxz)
    deallocate(qlm_em_ddgyyxz)
    deallocate(qlm_em_ddgyzxz)
    deallocate(qlm_em_ddgzzxz)
    deallocate(qlm_em_ddgxxyy)
    deallocate(qlm_em_ddgxyyy)
    deallocate(qlm_em_ddgxzyy)
    deallocate(qlm_em_ddgyyyy)
    deallocate(qlm_em_ddgyzyy)
    deallocate(qlm_em_ddgzzyy)
    deallocate(qlm_em_ddgxxyz)
    deallocate(qlm_em_ddgxyyz)
    deallocate(qlm_em_ddgxzyz)
    deallocate(qlm_em_ddgyyyz)
    deallocate(qlm_em_ddgyzyz)
    deallocate(qlm_em_ddgzzyz)
    deallocate(qlm_em_ddgxxzz)
    deallocate(qlm_em_ddgxyzz)
    deallocate(qlm_em_ddgxzzz)
    deallocate(qlm_em_ddgyyzz)
    deallocate(qlm_em_ddgyzzz)
    deallocate(qlm_em_ddgzzzz)
    deallocate(qlm_em_kxx)
    deallocate(qlm_em_kxy)
    deallocate(qlm_em_kxz)
    deallocate(qlm_em_kyy)
    deallocate(qlm_em_kyz)
    deallocate(qlm_em_kzz)
    deallocate(qlm_em_dkxxx)
    deallocate(qlm_em_dkxyx)
    deallocate(qlm_em_dkxzx)
    deallocate(qlm_em_dkyyx)
    deallocate(qlm_em_dkyzx)
    deallocate(qlm_em_dkzzx)
    deallocate(qlm_em_dkxxy)
    deallocate(qlm_em_dkxyy)
    deallocate(qlm_em_dkxzy)
    deallocate(qlm_em_dkyyy)
    deallocate(qlm_em_dkyzy)
    deallocate(qlm_em_dkzzy)
    deallocate(qlm_em_dkxxz)
    deallocate(qlm_em_dkxyz)
    deallocate(qlm_em_dkxzz)
    deallocate(qlm_em_dkyyz)
    deallocate(qlm_em_dkyzz)
    deallocate(qlm_em_dkzzz)
    deallocate(qlm_em_alpha)
    deallocate(qlm_em_betax)
    deallocate(qlm_em_betay)
    deallocate(qlm_em_betaz)
    deallocate(qlm_em_ttt)
    deallocate(qlm_em_ttx)
    deallocate(qlm_em_tty)
    deallocate(qlm_em_ttz)
    deallocate(qlm_em_txx)
    deallocate(qlm_em_txy)
    deallocate(qlm_em_txz)
    deallocate(qlm_em_tyy)
    deallocate(qlm_em_tyz)
    deallocate(qlm_em_tzz)
    deallocate(qlm_em_ex)
    deallocate(qlm_em_ey)
    deallocate(qlm_em_ez)
    deallocate(qlm_em_ax)
    deallocate(qlm_em_ay)
    deallocate(qlm_em_az)
    deallocate(qlm_em_daxx)
    deallocate(qlm_em_daxy)
    deallocate(qlm_em_daxz)
    deallocate(qlm_em_dayx)
    deallocate(qlm_em_dayy)
    deallocate(qlm_em_dayz)
    deallocate(qlm_em_dazx)
    deallocate(qlm_em_dazy)
    deallocate(qlm_em_dazz)
    deallocate(qlm_em_phi1)
    deallocate(qlm_em_phi2)
    
    deallocate(qlm_em_dqttt)
    deallocate(qlm_em_dqtpt)
    deallocate(qlm_em_dqppt)
    deallocate(qlm_em_dqttp)
    deallocate(qlm_em_dqtpp)
    deallocate(qlm_em_dqppp)
    
    deallocate(qlm_em_tetrad_derivs)

    deallocate(qlm_em_spin_density)
  end subroutine deallocate_variables

end module qlm_em_variables
